### ISSUE TITLE
Version 0.4.10 esp2866 stuck in boot loop 

### ISSUE THREAD

**Issue by gymnae** [lumapu/ahoy#56]
Tried uploading the sketch via OTA and then directly connected to my machine. 
The esp2866 gets stuck in a boot loop. Prior versions were fine, other sketches load fine as well:

```
09:53:33.806 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
09:53:33.806 -> 
09:53:33.806 -> load 0x4010f000, len 3460, room 16 
09:53:33.844 -> tail 4
09:53:33.844 -> chksum 0xcc
09:53:33.844 -> load 0x3fff20b8, len 40, room 4 
09:53:33.844 -> tail 4
09:53:33.844 -> chksum 0xc9
09:53:33.844 -> csum 0xc9
09:53:33.844 -> v0005a050
09:53:33.844 -> ~ld
09:53:33.918 -> Settings not valid, erasing ...
09:53:33.918 -> erase: 0x71 - 0xb1
09:53:33.918 -> erase: 0xb1 - 0xf1
09:53:33.918 -> erase: 0xf1 - 0x131
09:53:33.918 -> erase: 0x131 - 0x171
09:53:33.918 -> erase: 0x171 - 0x192
09:53:33.994 -> ... restarting ...
09:53:34.209 -> 
09:53:34.209 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
```

**Comment by lumapu** [comment]
ok I think I know the problem. Can you remove the erase function call inside main.cpp in setup()

**Comment by gymnae** [comment]
I'm sorry, I don't find what you want me to delete...

**Comment by lumapu** [comment]
I'm sorry it is here:

https://github.com/grindylow/ahoy/blob/main/tools/esp8266/main.cpp#L128

**Comment by gymnae** [comment]
Ah yeah, that fixed it :) 
Now it looks like this:
```
    else {
        /*mApActive = true;
        memset(mStationSsid, 0, SSID_LEN);
        memset(mStationPwd, 0, PWD_LEN);
        memset(mDeviceName, 0, DEVNAME_LEN);

        // erase application settings except wifi settings */
        snprintf(mStationSsid, SSID_LEN,    "%s", FB_WIFI_SSID);
        snprintf(mStationPwd,  PWD_LEN,     "%s", FB_WIFI_PWD);
        snprintf(mDeviceName,  DEVNAME_LEN, "%s", DEF_DEVICE_NAME);
    }
```

**Comment by stefan123t** [comment]
@lumapu upgraded from 0.4.5 to 0.4.10 tonight and also ran into this issue.

Please fix line 136 & 140 and not 128 (128 is inside a multiline comment already):
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/main.cpp#L136-L140
Otherwise the reboot continues indefinetly, somehow the eraseSettings() does not fill in zeros or does not clear the EEPROM area used for settings so it will continue after a Reset / ESP.reset().

I removed some settings by hand and used the "Erase all settings" button on the setup page to get all empty or "0".

I had to fill in my serial number and name again and add the new setting for each panel / channel max Wpp.
Why can I not set these things in config.h or how would I do that ?

I tried to use the original code after the settings were right, but it still rebooted. So I reverted to lines 136&140 commented out. 
Also in app.cpp lines 124-125 it complains about "Warn: your settings are not valid!"
https://github.com/grindylow/ahoy/blob/main/tools/esp8266/app.cpp#L124-L125

**Comment by lumapu** [comment]
hopefully fixed in 0.4.11

**Comment by stefan123t** [comment]
Still have this after flashing it again.
```
22:38:50.459 -> ... restarting ...
22:38:50.658 -> 
22:38:50.658 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
22:38:50.658 -> 
22:38:50.658 -> load 0x4010f000, len 3460, room 16 
22:38:50.658 -> tail 4
22:38:50.658 -> chksum 0xcc
22:38:50.658 -> load 0x3fff20b8, len 40, room 4 
22:38:50.658 -> tail 4
22:38:50.658 -> chksum 0xc9
22:38:50.658 -> csum 0xc9
22:38:50.658 -> v0005a820
22:38:50.658 -> ~ld
22:38:50.725 -> Settings not valid, erasing ...
22:38:50.725 -> erase: 0x71 - 0xb1
22:38:50.725 -> erase: 0xb1 - 0xf1
22:38:50.725 -> erase: 0xf1 - 0x131
22:38:50.725 -> erase: 0x131 - 0x171
22:38:50.725 -> erase: 0x171 - 0x192
22:38:50.824 -> ... restarting ...
```
unfortunately this is all rinse and repeat.
I will try again with an empty / original config.h ...

**Comment by stefan123t** [comment]
Okay needed to call buildEEpCrc() after eraseSetting() or saveValues().
Fixed and can be closed.

**Comment by stefan123t** [comment]
Hmm maybe still something wrong.
```
connect to network '⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮'
```
It now tries the empty / erased settings for its FB_WIFI_SSID and FB_WIFI_PWD.
Not exactly what we expected from setting this in config.h.
I will try to set it manually in /setup and save settings in EEprom.

**Comment by gymnae** [comment]
Version 0.4.13 works fine for me, updated via OTA

**Comment by stefan123t** [comment]
Here are pictures after connecting to the Access Point.
![Screenshot from 2022-05-29 23-25-12](https://user-images.githubusercontent.com/11159753/170892247-651c454b-9411-4258-843c-de6ee166b575.png)
![Screenshot from 2022-05-29 23-28-48](https://user-images.githubusercontent.com/11159753/170892250-a267a454-0f66-434b-95dd-96234a65f63b.png)
I had to setup everything new, even the wiring.

This is probably only necessary after the EEprom data structure changed.
After forcibly resetting the ESP the Crc checksums seemed to match according to the Debug line.
```
CRC RD: 1c79 CRC CALC: 1c79
23:40:06.329 -> CRC RD: 2593 CRC CALC: 2593
```

Nevertheless, the Wiring, MQTT and SSID should be saved with sane defaults after eraseSettings.

**Comment by stefan123t** [comment]
Die [sicheren Defaults in app.cpp](https://github.com/grindylow/ahoy/blob/247ae3e1db7c602dcea2548bf25b87d73c020b3b/tools/esp8266/app.cpp#L491-L504) werden offenbar nicht gesetzt sondern mit den "falschen" Defaults aus eraseSettings() und saveValues() ersetzt.

```
        html.replace(F("{INV_INTVL}"), "5");

        html.replace(F("{SER_VAL_CB}"), "checked");
        html.replace(F("{SER_DBG_CB}"), "");
        html.replace(F("{SER_INTVL}"), "10");

        html.replace(F("{MQTT_ADDR}"), "");
        html.replace(F("{MQTT_PORT}"), "1883");
        html.replace(F("{MQTT_USER}"), "");
        html.replace(F("{MQTT_PWD}"), "");
        html.replace(F("{MQTT_TOPIC}"), "inverter");
        html.replace(F("{MQTT_INTVL}"), "10");

        html.replace(F("{SER_INTVL}"), "10");
```

**Comment by lumapu** [comment]
ja der `else` Zweig kann jetzt nicht mehr erreicht werden, da die Settings jetzt immer valide sind (CRC wird beim erase aktualisiert). Hier brauchen wir ein neues Konzept um zu detektieren, dass frisch erased wurde.
